name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Make
      run: make
  
    - name: Valgrind Leak Check
      uses: solareenlo/42valgrind-action@v1.0.3
      with:
        flags: ./nhnt
          
